name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment on pull requests to the main branch
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    runs-on: ubuntu-latest  # Use a GitHub-hosted Ubuntu runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository's code

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1  # Install Terraform

    - name: Azure Login using Service Principal
      uses: azure/login@v1  # Authenticate using Service Principal
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Initialize Terraform
      run: terraform init  # Initialize the Terraform working directory

    - name: Terraform Plan
      run: terraform plan  # Generate and show an execution plan

    - name: Terraform Apply
      run: terraform apply -auto-approve  # Apply the plan without manual approval